### ISSUE TITLE
Sending Emails Fails

### ISSUE THREAD

**Issue by randre03** [harishkrupo/oauth2ms#5]
Hello, thanks for this package - finally able to work with email on emacs. Unfortunately, I am unable to send any emails.

I copied the code recommended in `steps.org` and added my smtp server details. When I try to send an email in emacs I am prompted for my password (rightly or wrongly, I was expecting to not be prompted, so I just hit `return`). It quickly fails after that. Here is what I can see (from the \*Messages\* buffer:
```
Sending...
530 5.7.57 Client not authenticated to send mail. [server.prod.outlook.com]
451 4.7.0 Temporary server error. Please try again later. PRX4  [server.prod.outlook.com]
221 2.0.0 Service closing transmission channel
smtpmail-send-it: Sending failed: 451 4.7.0 Temporary server error. Please try again later. PRX4 [server.prod.outlook.com] in response to AUTH
```

For more detail here is the trace of the SMTP session:
```
220 server.outlook.office365.com Microsoft ESMTP MAIL Service ready at Fri, 26 Feb 2021 22:05:56 +0000
250-server.outlook.office365.com Hello [98.217.221.170]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
220 2.0.0 SMTP server ready
250-server.outlook.office365.com Hello [98.217.221.170]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH LOGIN XOAUTH2
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
AUTH XOAUTH2 [...token..]  [note: the token matches the output of the most recent `oauth2ms --encode-xoauth2`]
451 4.7.0 Temporary server error. Please try again later. PRX4  [server.prod.outlook.com]
QUIT
221 2.0.0 Service closing transmission channel

Process smtpmail connection broken by remote peer
```
I appreciate any guidance you can provide. Thank you!

**Comment by harishkrupo** [comment]
>I copied the code recommended in steps.org and added my smtp server details. When I try to send an email in emacs I am prompted for my password (rightly or wrongly, I was expecting to not be prompted, so I just hit return).

Yeah, the smtp library always asks for the username and password, irrespective of the type of authentication it is going to use. For now I too hit enter twice (will need to investigate if we can disable that). The `250-AUTH LOGIN XOAUTH2` line in the log shows that it is using OAUTH2 for authentication.

> 451 4.7.0 Temporary server error. Please try again later. PRX4  [server.prod.outlook.com]

I have never faced this issue before but looking at the SMTP rfc: https://tools.ietf.org/html/rfc5321, it looks like it is an error with the smtp server and not with the client. Unfortunately, there isn't much information available on this. 
I found a [page](https://www.limilabs.com/blog/office365-temporary-server-error-please-try-again-later-prx4) which explains that this is due to incorrect smtp configuration on the server. Also make sure that STMP is enabled on your server. This [link](https://support.microsoft.com/en-us/office/server-settings-you-ll-need-from-your-email-provider-c82de912-adcc-4787-8283-45a1161f3cc3#bkmk_findserver) has more details on how to check.

Hope this helps. Sorry If this isn't very helpful.

**Comment by randre03** [comment]
Thanks for your reply. I'll chase down those possible solutions. If I find anything noteworthy I will report back, but since this is most likely not a client issue, I am closing. Again, thanks for the package!

**Comment by randre03** [comment]
I can confirm  (for my issue at least) the fix you linked to above - described [here](https://www.limilabs.com/blog/office365-temporary-server-error-please-try-again-later-prx4l) worked for me.

**Comment by harishkrupo** [comment]
Nice! Good to know that it helped.
